FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.15-amd64 AS build
COPY . /source
WORKDIR /source

RUN dotnet restore

RUN dotnet publish --configuration Release --output /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.15-amd64 AS base
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "MinitwitReact.dll"]