global using Microsoft.EntityFrameworkCore;
global using MinitwitReact.Core;
global using MinitwitReact.Entities;
global using Microsoft.AspNetCore.Mvc;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.ComponentModel.DataAnnotations;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;

global using MinitwitReact;
global using MinitwitReact.Core;
global using MinitwitReact.Extensions;
global using MinitwitReact.Authentication;
global using MinitwitReact.Core.IRepositories;
global using MinitwitReact.Core.DTO;
