FROM node:17-alpine as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

COPY . ./

RUN npm run build

FROM node:17-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=builder /app/build ./build
