services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - URL=minitwit.online
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean
      - EMAIL=eythor108@gmail.com
      - DHLEVEL=4096
    volumes:
      - ./letsencrypt:/config
    restart: unless-stopped

  frontend:

    container_name: react_frontend

    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev

    ports:
      - 3000:3000

    command: serve -s build -l 3000

    depends_on:
      - backend

    restart: on-failure
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest #mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  backend:

    container_name: dotnet_backend
    build:
      context: ./backend/MinitwitReact
      dockerfile: Dockerfile.dev
    ports:
      - 5229:80

    environment:
      ConnectionStrings__Minitwit:
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__Minitwit
    restart: on-failure
    
secrets:
  db_password:
    file: .local/db_password.txt
  connection_string:
    file: .local/connection_string.txt
  
