global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using MinitwitReact;
global using MinitwitReact.Entities;
global using Xunit;
global using MinitwitReact.Core.DTO;
global using MinitwitReact.Core;
global using MinitwitReact.Core.IRepositories;
global using MinitwitReact.Infrastructure.Repositories;