name: deploy

on:
  release:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore minitwit/backend
    - name: Build
      run: dotnet build minitwit/backend --no-restore
    - name: Test
      run: dotnet test minitwit/backend --no-build --verbosity normal

  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
        - name: Docker login
          run: |
             echo "LOGIN"
             echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: Docker Build and Push
          run: |
             echo "BUILD"
             docker build -t virginity/minitwit_frontend:latest . -f ./minitwit/backend/MinitwitReact/Dockerfile.dev
             docker build -t virginity/minitwit_backend:latest . -f ./minitwit/frontend/Dockerfile.dev
             echo "PUSH"
             docker push virginity/minitwit_frontend:latest
             docker push virginity/minitwit_backend:latest

        - name: Deploy to Digital Ocean
          run: |
             ssh -o "StrictHostKeyChecking no" ${{ secrets.MT_USER }}@${{ secrets.MT_SERVER }} -i ${{ secrets.SSH_KEY }}
             "source /root/.bash_profile && \
             cd /app/minitwit && \
             docker-compose pull && \
             docker-compose up -d"
