name: deploy

on:
   release:
     types: [published]
     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore minitwit/backend
    - name: Build
      run: dotnet build minitwit/backend --no-restore
    - name: Test
      run: dotnet test minitwit/backend --no-build --verbosity normal

  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
        - uses: actions/checkout@v2
        - name: Docker login
          run: |
             echo "LOGIN"
             echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
             
        - name: Docker Build and Push
          run: |
             echo "BUILD"
             cd minitwit/frontend
             docker build -t virginity/minitwit_frontend:latest . -f Dockerfile.dev
             cd ../backend/MinitwitReact
             docker build -t virginity/minitwit_backend:latest . -f Dockerfile.dev
             cd ../../../
             echo "PUSH"
             docker push virginity/minitwit_frontend:latest
             docker push virginity/minitwit_backend:latest
             
        - name: Deploy to Digital ocean
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.MT_SERVER }}
            username: ${{ secrets.MT_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script: |
              cd /app/minitwit
              git pull &&
              echo "Taking down frontend" &&
              docker stop react_frontend &&
              docker rm react_frontend &&
              echo "Taking down backend" &&
              docker stop dotnet_backend &&
              docker rm dotnet_backend &&
              echo "Pulling from hub" &&
              docker-compose -f compose.prod.yaml pull &&
              echo "Building containers" &&
              docker-compose -f compose.prod.yaml up --build -d &&
              echo "BIG CLAPS GJ Friends"
