name: .NET

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore minitwit/backend
      - name: Build
        run: dotnet build minitwit/backend --no-restore
      - name: Test
        run: dotnet test minitwit/backend --no-build --verbosity normal
