name: release_schedule

on:

  schedule:
  - cron: "0 20 * * 0"

jobs:
  #From: https://github.com/actions/create-release
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get week num
        id: week
        run: |
          FIRST=$( echo $(date +%W) | awk '{ print substr( $0, 1, 1 ) }'); \
          if [[ "$FIRST" = "0" ]]; \
          then echo "::set-output name=week::$(echo $(( $( echo $(date +%W) | awk '{ print substr( $0, 2, 1 ) }')-4 )))"; \
          else echo "::set-output name=week::$(echo $(( $(date +%W)-4 )))"; fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.week.outputs.week }}.0
          release_name: Weekly Release: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
